Update README.md
jozu-ai/kitops pull request #524
Opened 2024-10-10 08:07 UTC by kushal34712

fixed unnecessary lines and corrected the grammar

2024-10-10 13:38 UTC, gorkem requested changes

2024-10-10 13:38 UTC, gorkem commented on README.md
> ----
Can you remove these extra lines

2024-10-10 17:52 UTC, kushal34712 commented on README.md
> ----
i have did the same thing

2024-10-11 16:39 UTC, bmicklea commented
All PRs need to be associated with an issue that clearly outlines what problem it solves and what the preferred solution is (and why another option isn't acceptable).

2024-10-11 16:39 UTC, closed without merging